project:
  type: website
  output-dir: docs

website:
  title: "assignment-3-hgp26"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
      - cosmo
      - brand
    css: styles.css
    toc: true



